# _config.yml
title: AWS Zero to Architect
description: Blog series â€“ from Cloud 101 to production-grade architectures
theme: minima
logo: /assets/images/icons8-aws-logo-100.png
permalink: /:year/:month/:day/:title.html
url: "https://asiandevs.github.io/aws-zero-to-architect-blog"
baseurl: ""
header_pages:
  - about.md
plugins:
  - jekyll-feed
  - jekyll-seo-tag
main_index_url: "/#module-index"
defaults:
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: default
