title: AWS Zero to Architect
description: Blog series â€“ from Cloud 101 to production-grade architectures
theme: minima
logo: /assets/images/icons8-aws-logo-100.png          # optional
permalink: /:year/:month/:day/:title.html
url: "https://asiandevs.github.io"
baseurl: "/aws-zero-to-architect-blog"
header_pages:
  - about.md
plugins:
  - jekyll-feed
  - jekyll-seo-tag
defaults:
  - scope:
      path: ""
    values:
      layout: "default"

