# _config.yml
title: AWS Zero to Architect
description: Blog series â€“ from Cloud 101 to production-grade architectures
theme: minima
logo: /assets/images/icons8-aws-logo-100.png
permalink: /:year/:month/:day/:title.html
url: "https://asiandevs.github.io"

header_pages:
  - about.md
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Custom variable for main page link
# Add or replace this variable
main_index_url: "/aws-zero-to-architect-blog/#module-index"

defaults:
  - scope:
      path: ""
    values:
      layout: "default"

# Force custom layout for posts (overrides Minima)
defaults:
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: default

# Ensure baseurl for relative URLs
baseurl: ""
url: "https://asiandevs.github.io/aws-zero-to-architect-blog"
